#!/usr/bin/env python3
"""
Compute phonon band structure with phonopy for structure directories that have
FORCE_SETS (or FORCE_CONSTANTS) and POSCAR.

Writes in each structure directory:
  bands.conf   — path settings used for this run
  bands.yaml   — band structure (also band.yaml for phonopy-bandplot)
  (optional) FORCE_CONSTANTS if --write-fc

Usage:
  python3.13 scripts/run_phonopy_bands.py
  python3.13 scripts/run_phonopy_bands.py --copy-to results nodef cVac 2G
"""

from __future__ import annotations

import argparse
import shutil
import sys
import time
from pathlib import Path

# Default high-symmetry path in supercell reciprocal coordinates
# Γ(0,0,0) → X(½,0,0) → M(½,½,0) → Γ → R(½,½,½)
DEFAULT_PATHS = [
    [[0.0, 0.0, 0.0], [0.5, 0.0, 0.0]],
    [[0.5, 0.0, 0.0], [0.5, 0.5, 0.0]],
    [[0.5, 0.5, 0.0], [0.0, 0.0, 0.0]],
    [[0.0, 0.0, 0.0], [0.5, 0.5, 0.5]],
]
DEFAULT_LABELS = [r"$\Gamma$", "X", "M", r"$\Gamma$", "R"]
# path_connections: True continues the segment on the plot axis
DEFAULT_CONNECTIONS = [True, True, True, False]


def write_bands_conf(path: Path, npoints: int) -> None:
    text = f"""# Auto-generated by run_phonopy_bands.py
# Phonon bands on the 2x2x2 supercell reciprocal lattice (DIM = 1 1 1).
DIM = 1 1 1
PRIMITIVE_AXES = 1 0 0  0 1 0  0 0 1
BAND = 0.0 0.0 0.0  0.5 0.0 0.0  0.5 0.5 0.0  0.0 0.0 0.0  0.5 0.5 0.5
BAND_POINTS = {npoints}
BAND_LABELS = G X M G R
"""
    path.write_text(text)


def run_one(
    workdir: Path,
    npoints: int = 51,
    write_fc: bool = False,
) -> Path:
    from phonopy import load
    from phonopy.phonon.band_structure import get_band_qpoints

    workdir = workdir.resolve()
    poscar = workdir / "POSCAR"
    force_sets = workdir / "FORCE_SETS"
    force_constants = workdir / "FORCE_CONSTANTS"
    if not poscar.is_file():
        raise FileNotFoundError(f"missing {poscar}")
    if not force_sets.is_file() and not force_constants.is_file():
        raise FileNotFoundError(f"need FORCE_SETS or FORCE_CONSTANTS in {workdir}")

    t0 = time.time()
    kwargs: dict = dict(
        supercell_matrix=[[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        primitive_matrix="P",
        unitcell_filename=str(poscar),
        produce_fc=True,
    )
    if force_constants.is_file() and not force_sets.is_file():
        kwargs["force_constants_filename"] = str(force_constants)
    else:
        kwargs["force_sets_filename"] = str(force_sets)

    print(f"[{workdir.name}] loading phonopy …", flush=True)
    ph = load(**kwargs)
    print(
        f"[{workdir.name}] loaded in {time.time()-t0:.1f}s  natom={len(ph.unitcell)}",
        flush=True,
    )

    if write_fc:
        from phonopy.file_IO import write_FORCE_CONSTANTS

        fc_path = workdir / "FORCE_CONSTANTS"
        write_FORCE_CONSTANTS(ph.force_constants, filename=str(fc_path))
        print(f"[{workdir.name}] wrote {fc_path}", flush=True)

    write_bands_conf(workdir / "bands.conf", npoints)
    # keep legacy name in sync
    shutil.copy2(workdir / "bands.conf", workdir / "band.conf")

    qpoints = get_band_qpoints(DEFAULT_PATHS, npoints=npoints)
    ph.run_band_structure(
        qpoints,
        with_eigenvectors=False,
        is_band_connection=False,
        path_connections=DEFAULT_CONNECTIONS,
        labels=DEFAULT_LABELS,
    )
    print(f"[{workdir.name}] band structure in {time.time()-t0:.1f}s", flush=True)

    # Write both names: bands.yaml (requested) and band.yaml (phonopy-bandplot)
    out_bands = workdir / "bands.yaml"
    out_band = workdir / "band.yaml"
    # API writes relative to CWD
    import os

    cwd = Path.cwd()
    try:
        os.chdir(workdir)
        ph.write_yaml_band_structure(filename="bands.yaml")
        # duplicate as band.yaml for phonopy-bandplot default
        if out_bands.is_file():
            shutil.copy2(out_bands, out_band)
    finally:
        os.chdir(cwd)

    if not out_bands.is_file():
        raise RuntimeError(f"bands.yaml not written in {workdir}")

    print(
        f"[{workdir.name}] wrote {out_bands.name} + band.yaml + bands.conf  "
        f"({out_bands.stat().st_size // 1024} KiB)  elapsed={time.time()-t0:.1f}s",
        flush=True,
    )
    return out_bands


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument(
        "dirs",
        nargs="*",
        type=Path,
        help="structure directories (default: nodef cVac 2G under repo root)",
    )
    p.add_argument("--npoints", type=int, default=51, help="points per band segment (default 51)")
    p.add_argument("--write-fc", action="store_true", help="also write FORCE_CONSTANTS")
    p.add_argument(
        "--copy-to",
        type=Path,
        default=None,
        help="copy bands_<name>.yaml into this directory",
    )
    args = p.parse_args(argv)

    root = Path(__file__).resolve().parent.parent
    dirs = args.dirs if args.dirs else [root / s for s in ("nodef", "cVac", "2G")]

    for d in dirs:
        if not d.is_dir():
            print(f"ERROR: not a directory: {d}", file=sys.stderr)
            return 1
        out = run_one(d, npoints=args.npoints, write_fc=args.write_fc)
        if args.copy_to is not None:
            args.copy_to.mkdir(parents=True, exist_ok=True)
            dest = args.copy_to / f"bands_{d.name}.yaml"
            shutil.copy2(out, dest)
            print(f"[{d.name}] copied → {dest}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
